services:
  alloy:
    image: grafana/alloy:${ALLOY_VERSION:-v1.11.3}
    ports:
      - 12345:12345
      - 4317:4317
      - 4318:4318
    env_file:
      - .env
    environment:
      ALLOY_DEPLOY_MODE: docker
    volumes:
      - ./scenarios:${BASE_DIR:-/alloy-resources}/scenarios
      - ./modules:${BASE_DIR:-/alloy-resources}/modules
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /alloy-resources/scenarios/${SCENARIO:-hassos}
    extra_hosts:
      - "host.docker.internal:host-gateway"
